BEGIN;

ALTER TABLE player DROP COLUMN birth;
ALTER TABLE player DROP COLUMN player_stats_id;
ALTER TABLE player ADD COLUMN age INT(11) NOT NULL DEFAULT 0;

ALTER TABLE player ADD COLUMN potential int(11) NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN speed int(11) NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN passing int(11) NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN stamina int(11) NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN energy int(11) NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN crossing int(11) NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN heading int(11) NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN marking int(11) NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN shots int(11) NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN tackling int(11) NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN dribbling int(11) NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN goalkeeping int(11) NOT NULL DEFAULT 0;

COMMIT;