BEGIN;

CREATE TABLE system_parameter (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  sid VARCHAR(32) NOT NULL,
  pkey VARCHAR(30) NOT NULL,
  value VARCHAR(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

COMMIT;